version: "3.1"

services:
  #mongo:
  #  image: mongo
  #  ports:
  #    - 27017:27017
  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - "4566:4566"
  #     - "4571:4571"
  #     - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
  #   environment:
  #     - SERVICES=s3
  #     - DEBUG=true
  #     - DATA_DIR=/tmp/localstack/data
  #   volumes:
  #     - ./localstack/data:/tmp/localstack/
  project-ink:
    #image: project-ink-v2:dev
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - datahike:/project-ink-v2/db
    environment:
      - DATABASE_URL=postgres
  #postgres:
  #  image: postgres
  #  ports:
  #    - 5432:5432
  #  environment:
  #    - POSTGRES_USER=user
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_DATABASE=development
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
  # redis-insight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - 8001:8001

volumes:
  redis-data:
  datahike:
